yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit')
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/',
         LoginView.as_view(template_name='users/login.html'),
         name='login'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        related_name='posts',
        on_delete=models.SET_NULL
    )
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        labels = {'group': 'Группа', 'text': 'Сообщение'}
        texts = {'group': 'Выберете группу', 'text': 'Введите сообщение'}
        fields = ['group', 'text']

yatube/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PostForm
from .models import Group, Post, User

POSTS_PER_PAGE = settings.POSTS_PER_PAGE


def get_page_context(queryset, request):
    paginator = Paginator(queryset, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return {
        'paginator': paginator,
        'page_number': page_number,
        'page_obj': page_obj,
    }


def index(request):
    context = get_page_context(Post.objects.all(), request)
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    context = {
        'group': group,
        'posts': posts,
    }
    context.update(get_page_context(group.posts.all(), request))
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_count = Post.objects.select_related('author').count()
    context = {
        'author': author,
        'post_count': post_count
    }
    context.update(get_page_context(author.posts.all(), request))
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post_count = Post.objects.select_related('author').count()
    context = {
        'post': post,
        'post_count': post_count,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(request.POST or None)
    if form.is_valid():
        new_post = form.save(commit=False)
        new_post.author = request.user
        new_post.save()
        return redirect('posts:profile', new_post.author)
    context = {
        'form': form,
        'is_edit': False,
    }
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail',
                        post_id=post.id)
    context = {
        'form': form,
        'post': post,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)

yatube/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
<!-- templates/about/author.html -->
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<div class="container py-5">
  <h1>Коротко обо мне
  </h1>
    <p>
      Привет, меня зовут Искандер! 
    </p>
    <p>
      Я новичок в области программирования.
      Учиться кодить я начал в Яндекс.практикуме с марта 2022 года.
      Я ведь даже не представлял, что втянусь в мир "бэкенда",
      так как всю жизнь испытывал тягу химии и биологии.
      И вот я здесь со скрежетом в мозгу пытаюсь овладеть навыками программирования
    </p>
    <p>
      На момент написания статьи, прошло со старта обучения три месяца.
      Я уже обучился основам языка Python, работе с Django, с Git
    </p>
    <p>
      Все мои дальнейшие проекты можно отследить по
    <a href=https://github.com/IskanderRRR>ссылке</a>
    </p>
    <p>
    Всем чаю, господа
    </p>
    <p>
      <img src="/static/img/shkya.jpg" width="300" height="300">
    </p>
</div>
{% endblock %}

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
<div class="container py-5">
<div class="row">
  <h1>С чем мы работали</h1>
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <img src="/static/img/vsc.jpg" width="50" height="50">
        Visual Studio Code 
      </li>
      <li class="list-group-item">
        <img src="/static/img/py.png" width="50" height="50">
        Python 3.7.9 
      </li>
      <li class="list-group-item">
        <img src="/static/img/dj.png" width="50" height="50">
        Django 2.2.9
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <p>
      Огромная благодарность коллективу Яндекс.практикума, одногруппникам.<br>
      Особенно моему ревьюеру
    </p>
    <p>
      <img src="/static/img/pepe.webp" width="500" height="500">
    </p>
  </article>
</div>
</div>
{% endblock %} 

yatube/templates/base.html
{% load static %}
<!DOCTYPE html> 
<html lang="ru">          
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
      {% block title %}
      {% endblock title %}
    </title>
  </head>
  <body>       
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
    <footer>
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html> 

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
  <p>© {% now "Y" %} Copyright <span style="color:red">Ya</span>tube</p>    
</footer>

yatube/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      <ul class="nav nav-pills">
      {% with request.resolver_match.view_name as view_name %}
        <li class="nav-item active"> 
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" 
            href="{% url 'about:author' %}"
          >
            Об авторе
          </a>
        </li>
        <li class="nav-item active">
          <a class="nav-link {% if view_name == 'about:tech' %}active{% endif %}"
            href="{% url 'about:tech' %}"
          >
            Технологии
          </a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item active"> 
          <a class="nav-link {% if view_name == 'posts:post_create' %}active{% endif %}"
            href="{% url 'posts:post_create' %}"
          >
            Новая запись
          </a>
        </li>
        <li class="nav-item active"> 
          <a class="nav-link link-light" href="<!-- -->">Изменить пароль</a>
        </li>
        <li class="nav-item active"> 
          <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        </li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link {% if view_name == 'users:login' %}active{% endif %}"
            href="{% url 'users:login' %}"
          >
            Войти
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'users:signup' %}active{% endif %}"
            href="{% url 'users:signup' %}"
          >
            Регистрация
          </a> 
        </li>
        {% endif %}
      </ul>
      {% endwith %}
    </div>
  </nav>      
</header> 

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if edit %}
    Редактировать запись
  {% endif %}
    Добавить новую запись
{% endblock title %}
{% block content %}
{% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if edit %}
              Редактировать запись
            {% else %}
              Добавить новую запись
            {% endif %}             
          </div>
            <div class="card-body">
              <form action = "{% if edit %}
                {% url 'posts:post_edit' post_id=post.id %}
              {% else %}
                {% url 'posts:post_create' %}
              {% endif %}" method="post" enctype="multipart/form-data">
              </form>
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                    <label for="{{ field.id_for_label }}" class="col-md-2 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                    <div class="col-md-12">

                        {{ field|addclass:"form-control" }}

                        {% if field.texts %}
                        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.texts|safe }}</small>
                        {% endif %}
                    </div>
                </div>
              {% endfor %}                  
            </div>            
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                  {% if edit %}
                  Редактировать
                  {% else %}
                  Добавить
                  {% endif %}
              </button>
            </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
  {% block title %}
    {{ title }}
  {% endblock title %}
  {% block content %}
    <div class="container py-5">
      {% block header %} <h1>{{ group.title }}</h1>{% endblock %}
        <p>{{ group.description|linebreaksbr }}</p>
        <article>
      {% for post in page_obj %}
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
              <a href="{% url 'posts:profile' post.author.username %}"
              >
                все посты пользователя
              </a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p>{{ post.text|linebreaksbr }}</p>
          <p><a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>  
          </p>
          {% if post.group %}   
            <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
          {% endif %} 
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %} 
      {% include 'posts/includes/paginator.html' %}
    </div>
  {% endblock  %}

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
  {% block title %}
    {{ title }}
  {% endblock title %}
  {% block content %}
    <div class="container py-5">     
      <h1>Последние обновления на сайте</h1>
      <article>
        {% for post in page_obj %}
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
              <a href="{% url 'posts:profile' post.author.username %}"
              >
                все посты пользователя
              </a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p>{{ post.text }}</p>
          <p><a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>  
          </p>
          {% if post.group %}   
            <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
          {% endif %} 
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %} 
        {% include 'posts/includes/paginator.html' %}
      </article>
    </div>
  
  {% endblock content %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %}Пост {{ post.text|truncatewords:30 }} {% endblock %}
{% block content %}
{% load user_filters %}
    <div class="container py-5">
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>  
              <li class="list-group-item">
                Группа: {{ post.group.title }} 
                <a href="{% url 'posts:group_posts' post.group.slug %}">
                  все записи группы
                </a>
              </li>
              <li class="list-group-item">
                Автор: {{ post.author.get_full_name }}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ post_count }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author %}">
              все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>
            {{ post.text|linebreaksbr }}
          </p>
          {% if post.author == request.user %}
            <a href="{% url 'posts:post_edit' post.id %}">редактировать пост</a>
          {% endif %}
        </article>
      </div>
    </div> 
{% endblock content %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
    Профайл пользователя {{author.get_full_name}}
{% endblock title %}
{% block content %}
  <div class="container py-5">        
    <h1>Все посты пользователя {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ post_count }} </h3>
    <article>  
      {% for post in page_obj %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
          <p>
            {{ post.text }}
          </p>
        <p><a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>  
        </p>
        <p>
          {% if post.group %}   
            <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
          {% endif %}        
        </p>
        <hr>
        {% endfor %}
        {% include 'posts/includes/paginator.html' %} 
    </article>
  </div>
{% endblock content %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}
​
          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}
​
          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted"> 
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <a href="../users/password_reset_form.html" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
 </div> <!-- row -->
{% endblock %}
                

yatube/templates/users/password_change_done.html
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock title %}
{% block content %}
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Пароль изменён
              </div>
              <div class="card-body"> 
                <p>Пароль изменён успешно</p>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div>
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock title %}
{% block content %}
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Изменить пароль
              </div>
              <div class="card-body">
                <form method="post" action="../users/password_change_form.html">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">
                  <div class="form-group row my-3 p-3">
                    <label for="id_old_password">
                      Старый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      Новый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                      <small id="id_new_password1-help" class="form-text text-muted">
                        <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                      </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      Подтверждение нового пароля
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Изменить пароль
                    </button>
                  </div>
                </form>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div>
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock title %}
{% block content %}
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Восстановление пароля завершено
              </div>
              <div class="card-body">
                <p>Ваш пароль был сохранен. Используйте его для входа</p>
                <a href="../users/login.html">войти</a>
              </div> 
            </div> 
          </div>
        </div> 
      </div>
{% endblock %}

yatube/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock title %}
{% block content %}
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Отправлено письмо
              </div>
              <div class="card-body">
                <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
              </div> 
            </div> 
          </div>
        </div> 
      </div>
{% endblock %}

yatube/templates/users/signup.html
{% extends 'base.html' %}
  {% block title %}
    {{ title }}
  {% endblock title %}
  {% block content %}
      <div class="container py-5"> 
        <div class="row justify-content-center">
            <div class="col-md-8 p-5">
              <div class="card">
                <div class="card-header">
                  Зарегистрироваться
                </div>
                <div class="card-body">
                  <form method="post" action="{% url 'users:signup' %}">
                    <input type="hidden" name="csrfmiddlewaretoken" value="">
                    <div class="form-group row my-3 p-3">
                      <label for="id_first_name">Имя</label>    
                      <input type="text" name="first_name" maxlength="30" class="form-control" id="id_first_name">     
                    </div>
                    <div class="form-group row my-3 p-3">
                      <label for="id_last_name">Фамилия</label>    
                      <input type="text" name="last_name" maxlength="150" class="form-control" id="id_last_name">
                    </div>
                    <div class="form-group row my-3 p-3">
                      <label for="id_username">
                        Имя пользователя
                        <span class="required text-danger">*</span>
                      </label>    
                      <input type="text" name="username" maxlength="150" autofocus class="form-control" required id="id_username">
                        <small id="id_username-help" class="form-text text-muted">
                          Обязательное поле. Не более 150 символов. Только буквы, цифры и символы @/./+/-/_.
                        </small>
                    </div>
                    <div class="form-group row my-3 p-3">
                      <label for="id_email">Адрес электронной почты</label>    
                      <input type="email" name="email" maxlength="254" class="form-control" id="id_email">      
                    </div>
                    <div class="form-group row my-3 p-3">
                      <label for="id_password1">
                        Пароль        
                        <span class="required text-danger">*</span>
                      </label>    
                      <input type="password" name="password1" class="form-control" required id="id_password1">
                      <small id="id_password1-help" class="form-text text-muted">
                        <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                      </small>
                    </div>
                    <div class="form-group row my-3 p-3">
                      <label for="id_password2">
                        Подтверждение пароля
                        <span class="required text-danger">*</span>
                      </label>    
                      <input type="password" name="password2" class="form-control" required id="id_password2">
                      <small id="id_password2-help" class="form-text text-muted">
                        Для подтверждения введите, пожалуйста, пароль ещё раз.
                      </small>
                    </div>
                    <div class="col-md-6 offset-md-4">
                      <button type="submit" class="btn btn-primary">
                        Зарегистрироваться
                      </button>
                    </div>
                  </form>
                </div> <!-- card body -->
              </div> <!-- card -->
            </div> <!-- col -->
        </div> <!-- row -->
      </div>
  {% endblock %}    